### ISSUE TITLE
Use chips for tags in contest cards

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/hacker-blocks#1]
Current implementation - 
<img width="246" alt="screen shot 2017-04-15 at 10 45 58 am" src="https://cloud.githubusercontent.com/assets/1327050/25060986/e0cb1f5c-21c8-11e7-9d9f-c57abf37d27b.png">

What to implement ? 
See - https://material.io/guidelines/components/chips.html

**Comment by rahulyadav170923** [comment]
solved in https://github.com/coding-blocks/hacker-blocks/pull/10
