### ISSUE TITLE
Beautify error page

### ISSUE THREAD

**Issue by omerjerk** [coding-blocks/hacker-blocks#12]
<img width="1276" alt="screen shot 2017-05-30 at 12 02 07 pm" src="https://cloud.githubusercontent.com/assets/3191547/26570835/2d8036f4-4530-11e7-8377-91ef8630d266.png">

This error page needs to be modified.

**Comment by hereisnaman** [comment]
@omerjerk improved: https://github.com/coding-blocks/hacker-blocks/pull/13

bounty 100 or 50?

**Comment by omerjerk** [comment]
@hereisnaman 150. :P

**Comment by hereisnaman** [comment]
@omerjerk thanks :)
