### ISSUE TITLE
clicking on 'run' always shows error.

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/hacker-blocks#2]
<img width="723" alt="screen shot 2017-04-15 at 3 49 58 pm" src="https://cloud.githubusercontent.com/assets/1327050/25062884/59d892a6-21f3-11e7-94d1-f63174bcce08.png">

**Comment by championswimmer** [comment]
@omerjerk close if it is already fixed

**Comment by omerjerk** [comment]
Already fixed from backend.
