### ISSUE TITLE
Beautify problem status icons

### ISSUE THREAD

**Issue by omerjerk** [coding-blocks/hacker-blocks#23]
These icons need to be changed. As shown in the below screenshot.
Also, don't forget to delete the older ones.

<img width="1280" alt="screen shot 2017-06-15 at 2 04 31 pm" src="https://user-images.githubusercontent.com/3191547/27173085-17b9f29a-51d5-11e7-959d-4e7839cb1edd.png">

**Comment by sohini-roy** [comment]
thanks for the helpful description. I would like to work on this issue :)

**Comment by omerjerk** [comment]
@sohini-roy We would love your contribution. :)

**Comment by ArushiSinghal** [comment]
@omerjerk Are these icons visible to only Admin?

**Comment by omerjerk** [comment]
These get visible after you attempt a problem. A cross comes if you get a wrong answer, a yellow tick comes for partially solved problem and green tick comes for completely correct solution. So you'll have to solve a problem to see these icons.

**Comment by ArushiSinghal** [comment]
@omerjerk 
Is this icon looking better
![sample](https://user-images.githubusercontent.com/20858804/27380265-17ad4c22-569c-11e7-8d06-6e8301d6b631.png)

**Comment by ArushiSinghal** [comment]
@omerjerk 
For the wrong solution
![screenshot from 2017-06-21 16-36-55](https://user-images.githubusercontent.com/20858804/27381446-87e8af50-56a0-11e7-947b-fe81513fac42.png)
![screenshot from 2017-06-21 16-37-31](https://user-images.githubusercontent.com/20858804/27381449-89d52096-56a0-11e7-990c-4b1e38619c81.png)
![screenshot from 2017-06-21 16-38-25](https://user-images.githubusercontent.com/20858804/27381453-8bce7dd4-56a0-11e7-8713-932072aace43.png)
![screenshot from 2017-06-21 16-39-02](https://user-images.githubusercontent.com/20858804/27381456-8d8e9c8a-56a0-11e7-9131-6d22e2334c2a.png)
![screenshot from 2017-06-21 16-34-52](https://user-images.githubusercontent.com/20858804/27381459-8f470a08-56a0-11e7-876d-c4fbd0e2b10e.png)
![screenshot from 2017-06-21 16-34-03](https://user-images.githubusercontent.com/20858804/27381461-90b3e082-56a0-11e7-80d0-b2900303d574.png)

**Comment by ArushiSinghal** [comment]
@omerjerk we can also add the label to these icons. I am showing the example:-
![oie_c9iwcpzjysgo](https://user-images.githubusercontent.com/20858804/27384693-6eb13e5a-56ad-11e7-81bf-fb9a764e767d.png)

**Comment by omerjerk** [comment]
@ArushiSinghal The title is awesome. However, the icons need to be picked from material icon set. The material icon set is available here - https://material.io/icons/

And to use the icon in the code, you need to put the following line:

<i class="material-icons">warning</i>

**Comment by ArushiSinghal** [comment]
@omerjerk Now I have selected some of the icons from the material icon set. Please approve, I have attached screen-shots.
![screenshot from 2017-06-22 21-31-53](https://user-images.githubusercontent.com/20858804/27446678-1f1f11e2-579c-11e7-9d2e-e0647d65eaf1.png)
![screenshot from 2017-06-22 21-36-08](https://user-images.githubusercontent.com/20858804/27446685-23528e42-579c-11e7-8862-937e48403407.png)
![screenshot from 2017-06-22 21-38-30](https://user-images.githubusercontent.com/20858804/27446690-2780216e-579c-11e7-9108-04db61c000da.png)
![screenshot from 2017-06-22 22-07-22](https://user-images.githubusercontent.com/20858804/27446708-2fbc2e68-579c-11e7-80bb-10059c1c514b.png)
![screenshot from 2017-06-22 22-08-42](https://user-images.githubusercontent.com/20858804/27446711-3313c666-579c-11e7-98b6-d88f22055f17.png)
![screenshot from 2017-06-22 22-10-04](https://user-images.githubusercontent.com/20858804/27446719-380f98c0-579c-11e7-896c-47d6ef2d60d6.png)
![screenshot from 2017-06-22 22-11-21](https://user-images.githubusercontent.com/20858804/27446726-3f3e37f0-579c-11e7-9e0b-7fcefbc71107.png)
![screenshot from 2017-06-22 22-12-32](https://user-images.githubusercontent.com/20858804/27446734-425fcaca-579c-11e7-97c5-564853365df5.png)
![screenshot from 2017-06-22 22-44-54](https://user-images.githubusercontent.com/20858804/27446818-754b1cbe-579c-11e7-98a0-fd5bbf89ffee.png)
![screenshot from 2017-06-22 22-45-55](https://user-images.githubusercontent.com/20858804/27446878-9da2d742-579c-11e7-9d97-d66f9d7a1d91.png)

**Comment by omerjerk** [comment]
Can you please send a pull request so that I can see the code? Just choose any of the icons you like.

**Comment by aayusharora** [comment]
Closing via #36
