### ISSUE TITLE
Bug Report: Signup form accepts details of any length

### ISSUE THREAD

**Issue by anu0012** [coding-blocks/hacker-blocks#24]
Signup form is taking input like name, surname, email without any lower limit. Also, there is no restriction on username. It is accepting even a single character.

![screen shot 2017-06-15 at 4 39 53 pm](https://user-images.githubusercontent.com/17943805/27178673-dddb5f50-51e8-11e7-80cf-72040cf66708.png)

**Comment by omerjerk** [comment]
@anu0012 The above page is a part of single signon login server oneauth. Please move the issue to https://github.com/coding-blocks/oneauth

**Comment by anu0012** [comment]
I think it has been already mentioned there. I didn't see that before.
