### ISSUE TITLE
Bug Report: Online users list is not scrollable

### ISSUE THREAD

**Issue by anu0012** [coding-blocks/hacker-blocks#25]
I have tested it in chrome and it is not scrolling. 

![screen shot 2017-06-15 at 4 53 14 pm](https://user-images.githubusercontent.com/17943805/27179161-fb640ba6-51ea-11e7-9a61-10e83bb6d2e9.png)

**Comment by omerjerk** [comment]
Please fix it. :)
Contributions are always accepted.

**Comment by anu0012** [comment]
Hey @omerjerk will I get the bounty for the bug report also?
