### ISSUE TITLE
move `/practice` route to `/dcb` route (for Daily Code Bytes) and `/practice-section` to `/practice`

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/hacker-blocks#28]

**Comment by championswimmer** [comment]
@omerjerk this would look neat.

**Comment by ananay** [comment]
here you go!
https://github.com/coding-blocks/hacker-blocks/pull/29

**Comment by prateekiiest** [comment]
@championswimmer 
PR #30

**Comment by abhishek97** [comment]
@ananay @prateekiiest  both of your PR do quite a lot for such simple task. We need to just make the path visible to the user change. That doesn't necessarily mean to change the actual name of route/controller/templates structure in the code. Take a look at `app/router.js` and see how that works. This is quite easily a one-liner, however i leave it up to you. /

Also @omerjerk @championswimmer I do think we only need to change the path users sees right?

**Comment by ananay** [comment]
I don't think so. If it was that easy then they wouldn't have given 200
points for that.

**Comment by abhishek97** [comment]
@ananay Yeah. Fortunately this isn't a university exam. A 12 marks question may not necessarily mean a 5 page answer. I'm sure you can see that.

**Comment by omerjerk** [comment]
@abhishek97 May be this is good for the long run.

@prateekiiest @ananay Thanks for the change. I'll merge the one who did it early if I find everything else same.

**Comment by championswimmer** [comment]
From a product perspective, just changing the visible URL is okay with me. But final call with @omerjerk, if he thinks the controllers should be changed too, and it'll be better for future.

**Comment by omerjerk** [comment]
@ananay Issue a claim for 300 bounty points. I'll accept it.
