### ISSUE TITLE
When we go to contest page, the contest title show up on top

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/hacker-blocks#31]
For eg, go to https://hack.codingblocks.com/contests/c/31 
The name of the contest is not visible anywhere. 
<img width="1086" alt="banners_and_alerts_and_hacker_blocks" src="https://user-images.githubusercontent.com/1327050/27256012-c0d3c010-53c7-11e7-83f1-053be98b231f.png">

**Comment by hereisnaman** [comment]
resolved: https://github.com/coding-blocks/hacker-blocks/pull/32

**Comment by prateekiiest** [comment]
https://github.com/coding-blocks/hacker-blocks/pull/33
