### ISSUE TITLE
During "Sign Up" there should be either  Confirm Password or Show Password Option 

### ISSUE THREAD

**Issue by ArushiSinghal** [coding-blocks/hacker-blocks#38]
@aayusharora Please confirm

**Comment by aayusharora** [comment]
Valid issue @ArushiSinghal ? Do you like to work on this.

**Comment by ArushiSinghal** [comment]
yes @aayusharora .

**Comment by rishabh-bansal** [comment]
@ArushiSinghal  Can I work on this?

**Comment by ArushiSinghal** [comment]
@rishabh-bansal yes, please go ahead

**Comment by omerjerk** [comment]
Remember that login/signup is not part of hacker-blocks project. Please go to https://github.com/coding-blocks/oneauth for anything related to login/signup.
