### ISSUE TITLE
Add labels "Solved" and "Unsolved" for problems in the contest.

### ISSUE THREAD

**Issue by nkmishra1997** [coding-blocks/hacker-blocks#39]
As the number of problems grows, It becomes difficult to search for unsolved problems.
Something similar to the interface of Google Keep's List will be best.

**Comment by ArushiSinghal** [comment]
@nkmishra1997  I think if the problem is solved then it will show remarks like the wrong answer, correct answer and partially correct. So questions which are not marked that means they are unsolved.

**Comment by omerjerk** [comment]
^^ Agreed.

**Comment by nkmishra1997** [comment]
1.As the number of question grows in a contest, like more than 100, it becomes difficult to search for that terribly small 'tick' icon.
2.One needs to scroll entire list of questions to find which of them are solved and which of them are not solved.
Simply adding two (or maybe 3 labels) "Solved", "Unsolved" (3rd can be "Partially Solved") will help the participant to see unsolved questions easily.
