### ISSUE TITLE
Typo in content  

### ISSUE THREAD

**Issue by aayusharora** [coding-blocks/hacker-blocks#4]
## Issue 1
**Steps to reproduce**
 - Go to [hackerblock website](https://hack.codingblocks.com/courses)
 -  Click on Read More option of Django Course

**Output :  Page not found** 

## Issue 2

**Steps to reproduce**
 - Go to [hackerblock website Elixir Course](https://codingblocks.com/courses/elixir.html)
 -  Click on Javascript.
![python](https://cloud.githubusercontent.com/assets/12194719/25145756/76f66400-248f-11e7-8ecd-5cf395d53b41.png)

The word python should be replaced with Javascript.

**Comment by LakshmiSowndarya** [comment]
For Issue 1, the page is not there in the codingblocks/courses. Either it should be commented or removed

**Comment by omerjerk** [comment]
@aayusharora the 404 issue has been fixed. I'm closing this issue.
