### ISSUE TITLE
Create a SVG/Vectorised Logo of HackerBlocks using the image file

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/hacker-blocks#40]
![hacker_blocsk](https://user-images.githubusercontent.com/5269147/27514240-e37d07fe-59a1-11e7-9b73-d5b5ee680711.jpg)

**Comment by ArushiSinghal** [comment]
@prateek27 please review

**Comment by shreyateeza** [comment]
@prateek27 Is this issue resolved? Or it is open for BOSS 2018?

**Comment by AvaniVerma** [comment]
@prateek27 May I work on this one?

**Comment by till-tomorrow** [comment]
@prateek27 @championswimmer please close this issue if resolved.
