### ISSUE TITLE
There should be login|signup button in the chat dialogue box that floats into the screen when clicked

### ISSUE THREAD

**Issue by arvindkalra** [coding-blocks/hacker-blocks#46]
![hackerblocks](https://user-images.githubusercontent.com/29686907/27673788-2c1ee0ec-5cc0-11e7-8baa-f7e6c501bc66.png)
When the chat icon is clicked a new dialogue box floats in but the dialogue box says login to chat but nothing happens on clicking it. There must be a login\signup button there too..

**Comment by aayusharora** [comment]
@championswimmer @omerjerk Is this side window unuseful?

**Comment by omerjerk** [comment]
It is for chat. And I don't think that the login button would make much sense there.
