### ISSUE TITLE
Even if "logged out" from the account, and if click on login it's automatically "logged in"

### ISSUE THREAD

**Issue by ArushiSinghal** [coding-blocks/hacker-blocks#49]
If the user wants to log in from New Account, then it is difficult as on clicking login it automatically logged in to previous the account.
a) log_in
![screenshot from 2017-06-30 04-06-56](https://user-images.githubusercontent.com/20858804/27713771-ddd3bdbe-5d4a-11e7-8f9f-d2943e4a4374.png)
b) log_out
![screenshot from 2017-06-30 04-07-12](https://user-images.githubusercontent.com/20858804/27713813-0c86f806-5d4b-11e7-9ae5-cf71ea6e035d.png)
c) when again log_in, it automatically logged in without asking credentials.
![screenshot from 2017-06-30 04-07-30](https://user-images.githubusercontent.com/20858804/27713816-0fa07f1c-5d4b-11e7-939b-2581dcd0cef8.png)

**Comment by omerjerk** [comment]
@championswimmer Let know how can we fix this issue. This has to do with oneauth.
