### ISSUE TITLE
Login Button Not Clicking from the IDE page...

### ISSUE THREAD

**Issue by arvindkalra** [coding-blocks/hacker-blocks#52]
To attempt a question one needs to login... There is written login to attempt but one can not click... A button for login and sign up is present on the page which can be used on desktop... but when one is using the page on a mobile no Sign In / Sign Up button is present on the page.. So it is tough hence there needs to be a Sign Up or Sign In button or link in place of **Login to attempt**....

![final](https://user-images.githubusercontent.com/29686907/27872854-cd6d655c-61c7-11e7-975d-4c6e0ca0df62.png)

**Comment by himankbhalla** [comment]
Thanks for reporting. Resolved.
