### ISSUE TITLE
Major Issue Found: Launchpad LIVE videos downloadable!

### ISSUE THREAD

**Issue by rishabh-bansal** [coding-blocks/hacker-blocks#56]
Launchpad LIVE Course Videos are downloadable:

Steps Used:

1. Extraction of Videos links using chrome extension.
2. Video converted from .M3U8 to .MP4 format using the extracted links.

Issue reported to Prateek Sir( @prateek27  ) and the issue is solved.

**Comment by omerjerk** [comment]
@prateek27 I'm closing this.
