### ISSUE TITLE
Making the Cards same size

### ISSUE THREAD

**Issue by aayusharora** [coding-blocks/hacker-blocks#7]
- Make the cards of the courses same size using `CSS`.
![45](https://cloud.githubusercontent.com/assets/12194719/26167067/5ab6fdd8-3b53-11e7-897c-555ca23951f0.png)

**Comment by sohini-roy** [comment]
Thanks for the helpful description :)
i am facing a few problems while running this app locally 
1.  services/pn.js: line 8, col 20, 'PubNub' is not defined.
pubnub code hosted in CDN is already included in app/index.html
2.  router.js: line 9, col 14, 'ga' is not defined.
please help me figure this out.

**Comment by omerjerk** [comment]
@sohini-roy Which browser are your running the app on? I also faced some issues while testing in Firefox. Can you try Chrome one?

**Comment by sohini-roy** [comment]
i am trying on chrome. it shows "build successful" on my terminal but the webpage on my localhost says "This page doesn't exist or you are not authorized to view this page."

**Comment by omerjerk** [comment]
@sohini-roy Can you please try again?

**Comment by sohini-roy** [comment]
I just did :( 
when i tried "ember build" error "invalid version" came up 
i uninstalled and reinstalled ember as well as npm but it was of no use

**Comment by abhishek97** [comment]
@sohini-roy Hi, can you continue this discussion at https://gitter.im/coding-blocks/boss-2017-lobby please, as it is not relevant to this issue. You can also hit me on DM here: https://gitter.im/abhishek97 , i'll be happy to help you out.

**Comment by omerjerk** [comment]
@sohini-roy Please ping on gitter as @abhishek97 mentioned. :)

**Comment by ArushiSinghal** [comment]
@omerjerk @abhishek97  Is this issue still open?

**Comment by abhishek97** [comment]
@ArushiSinghal Yes, all contributions are welcome :)

**Comment by ArushiSinghal** [comment]
@abhishek97  @omerjerk 
This is preview of this solved issue please approve
![oie_n9cu1p4fr34n](https://user-images.githubusercontent.com/20858804/27404956-73bc8cc0-56ed-11e7-9dd4-e59e7555012c.png)

**Comment by omerjerk** [comment]
@ArushiSinghal Looks good. Please send a pull request.

**Comment by aayusharora** [comment]
Closing via #35
