### ISSUE TITLE
Enable Autocomplete in the Ace editor

### ISSUE THREAD

**Issue by rahulyadav170923** [coding-blocks/hacker-blocks#8]

**Comment by rahulyadav170923** [comment]
@omerjerk

**Comment by rahulyadav170923** [comment]
solved in https://github.com/coding-blocks/hacker-blocks/pull/10

**Comment by akansh97531** [comment]
is this issue still open

**Comment by omerjerk** [comment]
@akansh97531 This has been fixed.

May be you can work on this issue - https://github.com/coding-blocks/hacker-blocks/issues/7 :)
